### ISSUE TITLE
vue2.5.7版本安装引入后报错

### ISSUE THREAD

**Issue by note520** [xuelongqy/vue-easyrefresh#2]
vue.esm.js:591 [Vue warn]: Failed to mount component: template or render function not defined.
found in
---> <EasyRefresh>

是不是有版本要求？

**Comment by xuelongqy** [comment]
没有版本要求，demo用的是vue2.6的slot 方式。你需要使用vue2.5的slot 方式引用组件。你可以找找vue2.5和vue2.6的区别
