### ISSUE TITLE
添加展开 收起更多功能

### ISSUE THREAD

**Issue by wl95** [xuelongqy/vue-easyrefresh#5]
![image](https://user-images.githubusercontent.com/34021853/67078967-ef2b7f00-f1c4-11e9-9d5b-1d4c85dbc9a7.png)
![image](https://user-images.githubusercontent.com/34021853/67079045-108c6b00-f1c5-11e9-9258-b45b2361913a.png)
![image](https://user-images.githubusercontent.com/34021853/67079091-200bb400-f1c5-11e9-9351-32c7743a70ca.png)
点击收起页面的滚动条需要刷新下位置 麻烦问一下 我需要怎么做

**Comment by xuelongqy** [comment]
调用onResize方法，和触发刷新加载一样的用法
